//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_DB_Bank
    {
        public int Id { get; set; }
        public string BankName { get; set; }
        public string IFSC { get; set; }
    }
}
